POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0
POSTGRES_DB=judge0
POSTGRES_HOST=db
POSTGRES_PORT=5432

REDIS_PASSWORD=judge0
REDIS_HOST=redis
REDIS_PORT=6379

# Max request body size (10MB)
server_client_max_body_size=10M
