#!/usr/bin/env python3
"""
Extracts the whole DSA curriculum into JSON for the Go importer.

    python3 extract.py                # writes into ./extracted
    python3 extract.py --out somedir

Every `.py` file under the content root becomes one problem, including the
empty ones, which are emitted with status "pending" so the site can still show
the curriculum order. Standard library only.
"""

import argparse
import json
import sys
import warnings
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List

# Several files contain invalid escape sequences such as "\ "; they still parse,
# and the warnings would otherwise bury the summary.
warnings.simplefilter("ignore", SyntaxWarning)

from dsa_parser import TOOLING_FILES, parse_problem_file, strip_order_prefix
from dsa_schema import STATUS_SOLVED, Problem, Topic, to_dict
from topics_meta import FOLDER_TO_TOPIC, TOPIC_META

CONTENT_ROOT = Path(__file__).resolve().parent
IGNORED_DIRS = {"__pycache__", "extracted", ".git"}


def discover_files(root: Path) -> List[Path]:
    files = []
    for path in root.rglob("*.py"):
        # One folder is literally named "... Conditions.py", so glob alone is
        # not enough to tell a problem from a directory.
        if not path.is_file():
            continue
        if any(part in IGNORED_DIRS for part in path.relative_to(root).parts):
            continue
        if path.name in TOOLING_FILES:
            continue
        if len(path.relative_to(root).parts) < 2:
            continue  # tooling or stray scripts at the content root
        files.append(path)
    return files


def extract_problems(root: Path) -> tuple[List[Problem], List[dict]]:
    problems: List[Problem] = []
    errors: List[dict] = []

    for path in discover_files(root):
        try:
            problems.append(parse_problem_file(path, root))
        except Exception as exc:  # noqa: BLE001 - report and keep going
            errors.append({"file": str(path.relative_to(root)), "error": str(exc)})

    problems.sort(key=lambda problem: problem.sort_key)

    # Two files in one folder can slugify to the same id (for example "Find
    # Original Array from Doubled array" and "Find Original Array From Doubled
    # Array"). Suffix later duplicates so ids stay stable and unique.
    seen: Counter = Counter()
    for problem in problems:
        seen[problem.id] += 1
        if seen[problem.id] > 1:
            problem.id = f"{problem.id}-{seen[problem.id]}"

    return problems, errors


def build_topics(root: Path, problems: List[Problem]) -> List[Topic]:
    by_topic: Dict[str, List[Problem]] = defaultdict(list)
    for problem in problems:
        by_topic[problem.topic_id].append(problem)

    folder_by_id = {row[1]: row[0] for row in TOPIC_META}
    topics: List[Topic] = []

    for folder, topic_id, title, category, difficulty, icon, color, description in TOPIC_META:
        owned = by_topic.get(topic_id, [])
        sections: List[str] = []
        for problem in owned:
            head = problem.section_path[0] if problem.section_path else ""
            if head and head not in sections:
                sections.append(head)
        topics.append(
            Topic(
                id=topic_id,
                title=title,
                category=category,
                description=description,
                difficulty=difficulty,
                icon=icon,
                color=color,
                folder_path=folder,
                problem_count=len(owned),
                solved_count=sum(1 for p in owned if p.status == STATUS_SOLVED),
                sections=sections,
            )
        )

    unknown = set(by_topic) - set(folder_by_id)
    if unknown:
        print(f"warning: problems mapped to unknown topics: {sorted(unknown)}", file=sys.stderr)

    return topics


def write_coverage(path: Path, topics: List[Topic], problems: List[Problem]) -> None:
    by_topic: Dict[str, List[Problem]] = defaultdict(list)
    for problem in problems:
        by_topic[problem.topic_id].append(problem)

    total = len(problems)
    solved = sum(1 for p in problems if p.status == STATUS_SOLVED)

    lines = [
        "# DSA content coverage",
        "",
        "Generated by `extract.py`. A problem is pending when its source file is empty.",
        "",
        f"- Total problems: {total}",
        f"- With a solution: {solved}",
        f"- Pending: {total - solved}",
        "",
    ]

    for topic in topics:
        owned = by_topic.get(topic.id, [])
        pending = [p for p in owned if p.status != STATUS_SOLVED]
        lines.append(f"## {topic.title} ({topic.solved_count}/{topic.problem_count})")
        lines.append("")
        if not owned:
            lines.append("No files on disk.")
        elif not pending:
            lines.append("Complete.")
        else:
            for problem in pending:
                lines.append(f"- {problem.source_file}")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=str(CONTENT_ROOT), help="content root")
    parser.add_argument("--out", default=None, help="output directory")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    out_dir = Path(args.out).resolve() if args.out else root / "extracted"
    out_dir.mkdir(parents=True, exist_ok=True)

    problems, errors = extract_problems(root)
    topics = build_topics(root, problems)

    solved = sum(1 for p in problems if p.status == STATUS_SOLVED)
    (out_dir / "dsa_problems.json").write_text(
        json.dumps(
            {
                "metadata": {
                    "total": str(len(problems)),
                    "solved": str(solved),
                    "pending": str(len(problems) - solved),
                },
                "problems": [to_dict(p) for p in problems],
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    (out_dir / "dsa_topics.json").write_text(
        json.dumps({"topics": [to_dict(t) for t in topics]}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    write_coverage(out_dir / "coverage.md", topics, problems)

    error_file = out_dir / "errors.json"
    if errors:
        error_file.write_text(json.dumps(errors, indent=2, ensure_ascii=False), encoding="utf-8")
    elif error_file.exists():
        error_file.unlink()

    print(f"topics    : {len(topics)}")
    print(f"problems  : {len(problems)} ({solved} solved, {len(problems) - solved} pending)")
    print(f"solutions : {sum(len(p.solutions) for p in problems)}")
    print(f"errors    : {len(errors)}")
    print(f"output    : {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
