import {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  Binary,
  BookOpen,
  BookTemplate,
  Bot,
  Brain,
  Bug,
  Cat,
  CircleDot,
  Clock,
  Cloud,
  Code2,
  Combine,
  Compass,
  Container,
  Cpu,
  Database,
  Dices,
  DollarSign,
  Eye,
  Fingerprint,
  FlaskConical,
  FolderTree,
  Gauge,
  Gavel,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  Globe,
  HardDrive,
  Heart,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link2,
  Lock,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Network,
  Orbit,
  Package,
  Palmtree,
  Presentation,
  Radio,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Route,
  Save,
  Scale,
  Scissors,
  ScrollText,
  Search,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Siren,
  Sparkles,
  Split,
  Star,
  Target,
  TestTube2,
  Thermometer,
  ThumbsUp,
  Timer,
  TreeDeciduous,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Undo2,
  Users,
  Vote,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'bar-chart': BarChart3,
  bell: Bell,
  binary: Binary,
  'book-open': BookOpen,
  'book-template': BookTemplate,
  bot: Bot,
  brain: Brain,
  bug: Bug,
  cat: Cat,
  'circle-dot': CircleDot,
  clock: Clock,
  cloud: Cloud,
  code2: Code2,
  combine: Combine,
  compass: Compass,
  container: Container,
  cpu: Cpu,
  database: Database,
  dices: Dices,
  'dollar-sign': DollarSign,
  eye: Eye,
  fingerprint: Fingerprint,
  flask: FlaskConical,
  'folder-tree': FolderTree,
  gauge: Gauge,
  gavel: Gavel,
  'git-branch': GitBranch,
  'git-commit': GitCommitHorizontal,
  'git-merge': GitMerge,
  globe: Globe,
  'hard-drive': HardDrive,
  heart: Heart,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  lightbulb: Lightbulb,
  link2: Link2,
  lock: Lock,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  minimize: Minimize2,
  network: Network,
  orbit: Orbit,
  package: Package,
  palmtree: Palmtree,
  presentation: Presentation,
  radio: Radio,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  'rotate-cw': RotateCw,
  route: Route,
  save: Save,
  scale: Scale,
  scissors: Scissors,
  'scroll-text': ScrollText,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  siren: Siren,
  sparkles: Sparkles,
  split: Split,
  star: Star,
  target: Target,
  'test-tube': TestTube2,
  thermometer: Thermometer,
  'thumbs-up': ThumbsUp,
  timer: Timer,
  'tree-deciduous': TreeDeciduous,
  'tree-pine': TreePine,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  triangle: Triangle,
  undo2: Undo2,
  users: Users,
  vote: Vote,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Bell,
  Binary,
  BookOpen,
  BookTemplate,
  Bot,
  Brain,
  Bug,
  Cat,
  CircleDot,
  Clock,
  Cloud,
  Code2,
  Combine,
  Compass,
  Container,
  Cpu,
  Database,
  Dices,
  DollarSign,
  Eye,
  Fingerprint,
  FlaskConical,
  FolderTree,
  Gauge,
  Gavel,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  Globe,
  HardDrive,
  Heart,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link2,
  Lock,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Network,
  Orbit,
  Package,
  Palmtree,
  Presentation,
  Radio,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCw,
  Route,
  Save,
  Scale,
  Scissors,
  ScrollText,
  Search,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Siren,
  Sparkles,
  Split,
  Star,
  Target,
  TestTube2,
  Thermometer,
  ThumbsUp,
  Timer,
  TreeDeciduous,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Undo2,
  Users,
  Vote,
  Workflow,
  Wrench,
  Zap,
};

export function resolveAimlIcon(name?: string): LucideIcon {
  if (!name) return BookOpen;
  return iconMap[name] ?? BookOpen;
}
